import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {backgroundColor: 'rgb(20,35,61)'},
  headerView: {
    backgroundColor: '#114c96',
    borderBottomWidth: 0,
  },
  headerBody: {
    flex: 1,
  },
  headerTitle: {
    color: 'snow',
    textAlign: 'center',
    alignSelf: 'center',
    letterSpacing: 0,
    width: 200,
  },
  imgButton: {backgroundColor: 'transparent'},
  backButton: {width: 25, height: 25},
  settingButton: {width: 30, height: 30},
  mainView: {
    flex: 1,
    alignItems: 'center',
  },
  firstView: {
    width: 50,
    height: 140,
    alignItems: 'center',
    padding: 10,
    marginTop: 30,
  },
  firstAMBView: {
    width: 50,
    height: 70,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    // bordercolor: 'black',
  },
  firstAView: {
    width: 50,
    height: 70,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    // bordercolor: 'black',
    marginTop: 10,
  },
  firstText10: {marginTop: 10, color: 'white'},
  subViewMiddle: {
    flexDirection: 'row',
    width: 380,
    height: 50,
    marginTop: 70,
  },
  secondView: {
    flexDirection: 'row',
    width: 140,
    height: 50,
    alignItems: 'center',
    marginLeft: 0,
  },
  secondAMBView: {
    width: 70,
    height: 50,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    // bordercolor: 'black',
  },
  secondBViewLeft: {
    width: 70,
    height: 50,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    // bordercolor: 'black',
    marginLeft: 10,
  },
  middleText10: {marginLeft: 10, color: 'white'},
  thirdView: {
    flexDirection: 'row',
    width: 140,
    height: 50,
    alignItems: 'center',
    marginLeft: 50,
  },
  thirdBViewRight: {
    width: 70,
    height: 50,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    // bordercolor: 'black',
    marginLeft: 10,
  },
  thirdAMBView: {
    width: 70,
    height: 50,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    // bordercolor: 'black',
    marginLeft: 10,
  },
  forthView: {
    width: 50,
    height: 140,
    alignItems: 'center',
    padding: 10,
    marginTop: 10,
  },
  forthText10: {color: 'white'},
  forthCView: {
    width: 50,
    height: 70,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    // bordercolor: 'black',
    marginTop: 10,
  },
  forthAMBView: {
    width: 50,
    height: 70,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    // bordercolor: 'black',
    marginTop: 10,
  },
});
